#!/bin/bash
echo "🔍 Vercel Environment Variables Kontrol Listesi"
echo "=============================================="
echo ""
echo "Frontend (React App) için gerekli:"
echo "  ✅ REACT_APP_SUPABASE_URL"
echo "  ✅ REACT_APP_SUPABASE_ANON_KEY"
echo ""
echo "Backend (API Functions) için gerekli:"
echo "  ✅ SUPABASE_URL"
echo "  ✅ SUPABASE_ANON_KEY"
echo ""
echo "Güncel Key:"
echo "  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqanp2aWxpd3dsYmp4Zm5weHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTE0OTMsImV4cCI6MjA3NDQ2NzQ5M30.Mz1QxAZZz6POk7M5B8n9oM0-Pi2jSFJDLzhTT7cwPPE"
echo ""
echo "URL:"
echo "  https://xgyjhofakpatrqgvleze.supabase.co"
echo ""
echo "⚠️  Vercel Dashboard'da bu variable'ları kontrol edin!"
