#!/bin/bash
echo "🔍 Vercel Environment Variables Kontrol Listesi"
echo "=============================================="
echo ""
echo "Frontend (React App) için gerekli:"
echo "  ✅ REACT_APP_SUPABASE_URL"
echo "  ✅ REACT_APP_SUPABASE_ANON_KEY"
echo ""
echo "Backend (API Functions) için gerekli:"
echo "  ✅ SUPABASE_URL"
echo "  ✅ SUPABASE_ANON_KEY"
echo ""
echo "Güncel Key:"
echo "  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhneWpob2Zha3BhdHJxZ3ZsZXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MjA2NDEsImV4cCI6MjA3Njk5NjY0MX0.RB2QQkjtXaM-GaH0HXP_B14BIDm0Y-MvlvDpOt7V1sQ"
echo ""
echo "URL:"
echo "  https://xgyjhofakpatrqgvleze.supabase.co"
echo ""
echo "⚠️  Vercel Dashboard'da bu variable'ları kontrol edin!"
