#!/bin/bash
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 Terminal'de Streamtape Response Loglarını Arama"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  Bu script terminal'in canlı çıktısını okuyamaz."
echo "   Terminal'deki Vercel dev server çıktısını manuel kontrol etmelisiniz."
echo ""
echo "📋 Terminal'de Yapmanız Gerekenler:"
echo ""
echo "1️⃣  Terminal'de arama yapın (Cmd+F / Ctrl+F):"
echo "   → '📥 Streamtape upload response' yazın"
echo "   → 'Full Streamtape upload result' yazın"
echo "   → 'File ID not found' yazın"
echo ""
echo "2️⃣  Veya terminal scroll ile:"
echo "   → Upload %100'den sonraki satırları bulun"
echo ""
echo "3️⃣  Terminal çıktısını kopyalayın ve paylaşın!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
